# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm 9.6.0
        uses: pnpm/action-setup@v4
        with:
          version: "9.6.0"
      - name: Set up Node 20.5.0
        uses: actions/setup-node@v3
        with:
          node-version: "20.5.0"
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Test flowfiletools-js
        run: pnpm run --filter @nf2t/flowfiletools-js test
      - name: Build flowfiletools-js
        run: pnpm run --filter @nf2t/flowfiletools-js build       
      - name: Build nifitools-js
        run: pnpm run --filter @nf2t/nifitools-js build    
      - name: Build @nf2t/webtools
        run: pnpm run --filter @nf2t/webtools build
      - name: Install NextJS version
        run: pnpm run --filter @nf2t/nf2t-webtools build
      - name: Make NextJS dist directory
        run: mkdir --parents ./apps/webtools/dist/vintagestory
      - name: Copy NextJS to dist directory
        run: cp -r ./apps/nf2t-webtools/out/* ./apps/webtools/dist/vintagestory
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist repository
          path: './apps/webtools/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
